### ISSUE TITLE
Getting Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found

### ISSUE THREAD

**Issue by prettytamben** [lekoala/silverstripe-uuid#1]
Hey! 

We are getting an error when trying to post the extended dataobject through api:
We are on SS 4.3.3
Error trace is below:
`ERROR [Emergency]: Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found
IN POST /api/submittedform
Line 32 in /vendor/lekoala/silverstripe-uuid/src/UuidExtension.php

Source
======
  23:      /**
  24:       * Assign a new uuid to this record. This will overwrite any existing uuid.
  25:       *
  26:       * @param string $field The field where the Uuid is stored in binary format
  27:       * @param bool $check Check if the uuid is already taken
  28:       * @return string The new uuid
  29:       */
  30:      public function assignNewUuid($field = 'Uuid', $check = true)
  31:      {
* 32:          $uuid = Uuid::uuid4();
  33:          if ($check) {
  34:              $schema = DataObjectSchema::create();
  35:              $table = $schema->tableName(get_class($this->owner));
  36:              do {
  37:                  $this->owner->Uuid = $uuid->getBytes();
  38:                  // If we have something, keep checking

Trace
=====
LeKoala\Uuid\UuidExtension->assignNewUuid()
UuidExtension.php:133

LeKoala\Uuid\UuidExtension->onBeforeWrite(, , , , , , )
Extensible.php:464

SilverStripe\View\ViewableData->extend(onBeforeWrite, )
DataObject.php:1191

SilverStripe\ORM\DataObject->onBeforeWrite()
SubmittedBriefingForm.php:295

SubmittedBriefingForm->onBeforeWrite()
DataObject.php:1337

SilverStripe\ORM\DataObject->preWrite()
DataObject.php:1519

SilverStripe\ORM\DataObject->write(, , , )
DefaultQueryHandler.php:447

Colymba\RESTfulAPI\QueryHandlers\DefaultQueryHandler->updateModel(SubmittedBriefingForm, 0, SilverStripe\Control\HTTPRequest)
DefaultQueryHandler.php:346

Colymba\RESTfulAPI\QueryHandlers\DefaultQueryHandler->createModel(Submittedbriefingform, SilverStripe\Control\HTTPRequest)
DefaultQueryHandler.php:175

Colymba\RESTfulAPI\QueryHandlers\DefaultQueryHandler->handleQuery(SilverStripe\Control\HTTPRequest)
RESTfulAPI.php:340

Colymba\RESTfulAPI\RESTfulAPI->index(SilverStripe\Control\HTTPRequest)
RequestHandler.php:323

SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, index)
Controller.php:284

SilverStripe\Control\Controller->handleAction(SilverStripe\Control\HTTPRequest, index)
RequestHandler.php:202

SilverStripe\Control\RequestHandler->handleRequest(SilverStripe\Control\HTTPRequest)
Controller.php:212

SilverStripe\Control\Controller->handleRequest(SilverStripe\Control\HTTPRequest)
Director.php:361

SilverStripe\Control\Director->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)
VersionedHTTPMiddleware.php:41

SilverStripe\Versioned\VersionedHTTPMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
BasicAuthMiddleware.php:68

SilverStripe\Security\BasicAuthMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AuthenticationMiddleware.php:61

SilverStripe\Security\AuthenticationMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
CanonicalURLMiddleware.php:188

SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPCacheControlMiddleware.php:42

SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
ChangeDetectionMiddleware.php:27

SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
FlushMiddleware.php:29

SilverStripe\Control\Middleware\FlushMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
RequestProcessor.php:66

SilverStripe\Control\RequestProcessor->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
SessionMiddleware.php:20

SilverStripe\Control\Middleware\SessionMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
AllowedHostsMiddleware.php:60

SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
TrustedProxyMiddleware.php:176

SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\Director->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
Director.php:370

SilverStripe\Control\Director->handleRequest(SilverStripe\Control\HTTPRequest)
HTTPApplication.php:48

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
HTTPApplication.php:66

SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(SilverStripe\Control\HTTPRequest)

call_user_func(Closure, SilverStripe\Control\HTTPRequest)
ErrorControlChainMiddleware.php:73

SilverStripe\Core\Startup\ErrorControlChainMiddleware->SilverStripe\Core\Startup\{closure}(SilverStripe\Core\Startup\ErrorControlChain)

call_user_func(Closure, SilverStripe\Core\Startup\ErrorControlChain)
ErrorControlChain.php:235

SilverStripe\Core\Startup\ErrorControlChain->step()
ErrorControlChain.php:225

SilverStripe\Core\Startup\ErrorControlChain->execute()
ErrorControlChainMiddleware.php:92

SilverStripe\Core\Startup\ErrorControlChainMiddleware->process(SilverStripe\Control\HTTPRequest, Closure)
HTTPMiddlewareAware.php:62

SilverStripe\Control\HTTPApplication->SilverStripe\Control\Middleware\{closure}(SilverStripe\Control\HTTPRequest)
HTTPMiddlewareAware.php:65

SilverStripe\Control\HTTPApplication->callMiddleware(SilverStripe\Control\HTTPRequest, Closure)
HTTPApplication.php:67

SilverStripe\Control\HTTPApplication->execute(SilverStripe\Control\HTTPRequest, Closure, )
HTTPApplication.php:49

SilverStripe\Control\HTTPApplication->handle(SilverStripe\Control\HTTPRequest)
index.php:25`

**Comment by lekoala** [comment]
looks like your vendors are not there

Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found

means a class is missing. make sure you run composer update

**Comment by prettytamben** [comment]
Thanks for the quick response. I installed the module via composer and it looks like the vendors are there. What else could possible go wrong? Should I install ramsey/uuid separately? If yes which ramsey/uuid version should I install?

**Comment by lekoala** [comment]
@prettytamben ok i see it seems that Ramsey\Uuid has been updated to version 4 and there are breaking changes
please restrict it to version 3 it should be fine
I'll update the composer package to reflect this

**Comment by prettytamben** [comment]
Thanks! I tested with 3.7-3.9 but I still bump into this issue. I have no idea what is happening here... I see ramsey's module had namespacing issues in the past, maybe it is cursed :)
I'm out of ideas the Ramsey\Uuid is completely invisible to the extension

**Comment by lekoala** [comment]
Do you see the class in your vendor directory ? There is no reason why composer autoloading wouldn't work. I'll check out if there is something wrong with recent versions of Ramsey/uuid I haven't tried with the latest updates

**Comment by prettytamben** [comment]
It eventually succeeded with Ramsey\Uuid 3.9.3

**Comment by lekoala** [comment]
@prettytamben  i'm glad it finally works :-) i've updated the composer.json file to reflect this. I'll check version 4 later, it seems interesting!
